http_path = "/"
css_dir = "../"
sass_dir = "."
images_dir = "../images"
fonts_dir = "../fonts"
javascripts_dir = "../js"
output_style = :expanded #:compressed
relative_assets=true
line_comments = false
